### ISSUE TITLE
code blocks don't get evaluated with latest version of websocket

### ISSUE THREAD

**Issue by agarwal** [andrewray/iocaml#29]
As discussed via email, websocket 0.9.1 + iocaml 0.4.7 doesn't work. Hitting shift+enter in a code cell does nothing but add a newline. It works if I downgrade to websocket 0.8.1 + iocaml 0.4.6.

**Comment by andrewray** [comment]
Turns out we hit a very old bug in Unix.ml getsockopt.

Ocamls been fixed and hopefully we might get a patched websocket to tide us over until the next release.

**Comment by agarwal** [comment]
For reference, related issues are: vbmithr/ocaml-websocket#24 and ocaml/ocaml#143.

**Comment by andrewray** [comment]
Tested and working after an opam update to websocket 0.9.2

**Comment by agarwal** [comment]
Thanks.
