### ISSUE TITLE
Install issue of iocaml-kernel 

### ISSUE THREAD

**Issue by pierregobin** [andrewray/iocaml#30]
When trying to install iocaml (via opam install iocaml) - installation process is failing for iocaml-kernel. The failure is occuring when compiling a c code:

   iocaml_zmq_stubs.c: In function ‘iocaml_zmq_msg_recv’
   iocaml_zmq_stubs.c:22:3: attention : implicit declaration of function ‘zmq_msg_recv’ [-Wimplicit-function-declaration]
    ret = zmq_msg_recv(msg, socket, flags);

The issue seems related to -Wall of gcc (when I remove this option, I manage to compile this c code - but I do not understand why I got this error message as the supposedly missing declaration is in /usr/include/zmq.h). Note : gcc 4.8.3 on Linux Fedora20.

Is there a way to install iocaml without such issue ?

**Comment by andrewray** [comment]
I guess you do not have the zeromq 3 (or 4) development package installed.

(although its now compiling, I think you are just deferring the error until runtime).

**Comment by pierregobin** [comment]
You got it ! thx !
