### ISSUE TITLE
'constructor' not allowed as a variable name

### ISSUE THREAD

**Issue by yallop** [andrewray/iocaml#32]
To reproduce: type

```
let constructor = 3
```

in a notebook (e.g. http://andrewray.github.io/iocamljs/min.html).  The cell freezes after the 'o'.

**Comment by andrewray** [comment]
Confirmed.  Seems to be a problem with the codemirror editor as it can be also seen here;

http://codemirror.net/mode/mllike/index.html

codemirror/CodeMirror#3106

**Comment by andrewray** [comment]
Fixed in repo and online.

**Comment by yallop** [comment]
Thanks!
