### ISSUE TITLE
No response from iocaml kernel in jupyter 4.1.0

### ISSUE THREAD

**Issue by ysalmon** [andrewray/iocaml#40]
I am starting to use IOCaml and Jupyter.
I installed IOCaml from opam, created a kernel.json file with the following
```
{
"display_name": "OCaml",
"language": "ocaml",
"argv": [
   "/home/yann/.opam/iocaml/iocaml.top",
    "-log",
    "iocaml.log",
    "-object-info",
    "-completion",
    "-connection-file",
    "{connection_file}"
]
}
```

When I run a iocaml notebook in jupyter, the kernel appears to be connected correctly (I solved the signature problem with ```--Session.key="b''"```). However, when I validate a code cell, nothing interesting seems to happen : the ```In[ ]:``` becomes ```In[*]:``` instead of receiving a number, an there is no output and no error message.

Running the iocaml executable works fine but at some point I want to export my notebook to html, latex etc. which this executable does not seems able to do.

**Comment by andrewray** [comment]
Are you sure the path to iocaml.top is correct?  I would expect it to be `/home/yann/.opam/<switch>/bin/iocaml.top`.

See also #37 and the gist I uploaded for jupyter and iocaml.  I note I use a slightly different way to disable the key.

**Comment by ysalmon** [comment]
Yes, iocaml is a symlink to my current opam switch (to avoid redefining the kernel in jupyter when I switch).

Just to be sure, I modified this to use ```~/.opam/4.02.0+improved-errors/bin```, to no avail. Changing the command line as in #37 did not help (but maybe I did it wrong ; I do not know gist or docker and inferred the meaning of the file).

The iocaml.log file contains the following : 
```
iocaml log file: 28/5/2016 23:10:55
open and bind socket tcp://127.0.0.1:32968
open and bind socket tcp://127.0.0.1:33259
open and bind socket tcp://127.0.0.1:50046
open and bind socket tcp://127.0.0.1:60804
open and bind socket tcp://127.0.0.1:38074
^@<F4><B0><DC>Q
<IDS|MSG>
  HMAC: 
  header: {"date":"2016-05-28T23:10:55.754558","username":"yann","session":"5EBC5AD8683B47B18AE6563DD9922CA3","msg_id":"c4df1964-49a2-4887-9e46-f461e6c5f2d7","msg_type":"kernel_info_request"}
  parent: {}
  content: {}
SEND
^@<F4><B0><DC>Q
<IDS|MSG>
  HMAC: 
  header: {"date":"2016-05-28T23:10:55.754558","username":"yann","session":"5EBC5AD8683B47B18AE6563DD9922CA3","msg_id":"729e8d6a-5756-4637-a432-483625424e23","msg_type":"kernel_info_reply"}
  parent: {"date":"2016-05-28T23:10:55.754558","username":"yann","session":"5EBC5AD8683B47B18AE6563DD9922CA3","msg_id":"c4df1964-49a2-4887-9e46-f461e6c5f2d7","msg_type":"kernel_info_request"}
  content: {"protocol_version":[3,2],"language_version":[4,1,0],"language":"ocaml"}
5EBC5AD8683B47B18AE6563DD9922CA3
<IDS|MSG>
  HMAC: 
  header: {"date":"2016-05-28T23:10:55.774046","username":"username","session":"5EBC5AD8683B47B18AE6563DD9922CA3","msg_id":"F3C288EA9EF34B63817176CECF3FAB3E","msg_type":"kernel_info_request"}
  parent: {}
  content: {}
SEND
5EBC5AD8683B47B18AE6563DD9922CA3
<IDS|MSG>
  HMAC: 
  header: {"date":"2016-05-28T23:10:55.774046","username":"username","session":"5EBC5AD8683B47B18AE6563DD9922CA3","msg_id":"dfd980e0-1e5f-447c-849a-e8569555087d","msg_type":"kernel_info_reply"}
  parent: {"date":"2016-05-28T23:10:55.774046","username":"username","session":"5EBC5AD8683B47B18AE6563DD9922CA3","msg_id":"F3C288EA9EF34B63817176CECF3FAB3E","msg_type":"kernel_info_request"}
  content: {"protocol_version":[3,2],"language_version":[4,1,0],"language":"ocaml"}
Exception: Ag_oj_run.Error("Line 1:\nMissing record field user_variables")
```

**Comment by ysalmon** [comment]
As you reported, a recent PR corrected this problem. However, for a reason that I do not understand, the 4.02.0+improved-errors opam switch does not seem to provide this corrected version of iocaml-kernel — switch 4.02.3 does.

Should I report this to opam ?

**Comment by andrewray** [comment]
There will be a package version issue with one of the many, many dependencies - maybe camlp4?  

I wonder if it works with plain ocaml 4.02.0?

I guess you can try reporting the issue with the +improved-errors switch, though I am not sure that it is actively maintained.

Perhaps you can build notebooks using iocaml (server) with +improved-errors then use 4.02.3+jupyter to perform the final export you want?

**Comment by ysalmon** [comment]
Thanks, but the package has been updated in opam meanwhile (I did not think to check for an update because my problems appeared as soon as I installed iocaml-kernel and I assumed that the package was up-to-date then).
