### ISSUE TITLE
Output cells should have a "stream" output as well as "data", to support conversion ?

### ISSUE THREAD

**Issue by Naereen** [andrewray/iocaml#59]
Hi again,

### Issue
I encountered the following issue when converting an IOCaml notebook to tex/pdf : almost all the output cells aren't rendered correctly.
In fact, the *typing* part of the output cells (with syntax coloring) are just not seen by `jupyter-nbconvert`.

### Examples
Here is an example, of a cell which produce both a stdout text and a type indication:
 ```json
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The OCaml toplevel, version 4.02.3\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<pre style=\"color:slategray;max-height:100px;overflow:hidden\" \n",
       "onclick=\"\n",
       "if (this.style.maxHeight === 'none') \n",
       "    this.style.maxHeight = '100px';\n",
       "else\n",
       "    this.style.maxHeight = 'none'; \n",
       "\">- : int = 0\n",
       "</pre>"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "Sys.command \"ocaml -version\";;"
   ]
  }
```
And when converting to PDF, only the stdout output has been seen and converted:
![notypinginoutputcells](https://cloud.githubusercontent.com/assets/11994719/24754083/4edeee42-1ad5-11e7-9b40-0aff271320a4.png)

It starts to be more bothering for cells which output just a type indication:
![notypinginoutputcells2](https://cloud.githubusercontent.com/assets/11994719/24754128/75d227f8-1ad5-11e7-8a7c-98cf9dca832f.png)

And even more for cells which compute something but not print it:
![notypinginoutputcells3](https://cloud.githubusercontent.com/assets/11994719/24754197/c056dad0-1ad5-11e7-9b24-2379df5640b2.png)
(example are from [this notebook](https://github.com/Naereen/notebooks/blob/master/agreg/Contraintes_temporelles.ipynb), if you need to check the code)

The code generating the output for type indication is [exec.ml#98, function html_of_status](https://github.com/andrewray/iocaml/blob/master/exec.ml#L98).

### Questions
- Was it intentional to treat differently the stdout outputs and the type indications?
- Is it mandatory ?
- Do you see any way of (easily) fixing this issue ?

> Thanks in advance!

**Comment by Naereen** [comment]
Hi @andrewray,
Any update please?

**Comment by jaredly** [comment]
Looks like the pdf conversion doesn't like html blocks -- that makes sense.
One quick fix would be to add a `text/plain` section to that output block. that way it would show the fancy html on the web, but it would still have some output in pdf

**Comment by Naereen** [comment]
Hi,
Yes, exactly.

I guess the `iocaml/iocaml.ml` file should be changed, currently I think the line to change is [iocaml/iocaml.ml#L305](https://github.com/andrewray/iocaml/blob/2b6fe7af0c15e2c60b81c79cece348fbde472b4b/iocaml.ml#L305).

```ocaml
po_data = `Assoc [ "text/html", 
              `String (Exec.html_of_status message !output_cell_max_height) ];
```
→
```ocaml
po_data = `Assoc [ "text/html", 
              `String (Exec.html_of_status message !output_cell_max_height) ]
          ?? combine the two `Assoc pieces ??
          `Assoc [ "text/plain", 
              `String (Exec.plain_of_status message) ];
```
where in `exec.ml`, a new function `plain_of_message` should be defined:
```ocaml
let plain_of_message message =
    match message with
    | Ok(data)  | Error(data) -> escape_html  data
 ;;
```
And I don't know exactly what is this variant ``` `Assoc```, so I don't know how to combine/concatenate two of them.

**Comment by Naereen** [comment]
@jaredly Do you have any idea how to combine the two `"text/html"` and `"text/plain"` pieces to have only one `po_data` node?

**Comment by Naereen** [comment]
I haven't tested (and will probably be unable to, last times I tried to play with iocaml and compile myself I failed), but I guess ``` `Assoc``` takes a list of couples in argument, so the following will probably work:

```ocaml

po_data = `Assoc [
              "text/html",
                  `String (Exec.html_of_status message !output_cell_max_height);
              "text/plain",
                  `String (Exec.plain_of_status message)
              ]
```

**Comment by jaredly** [comment]
exactly

**Comment by Naereen** [comment]
OK, good.

Could you try it please (and merge it, as you apparently have rights on the repo)?

**Comment by Naereen** [comment]
Any update, @jaredly @andrewray ?

**Comment by Naereen** [comment]
@jaredly @andrewray so I got bored of waiting, and instead of starting an unmaintainable fork of iocaml, I made a small Python script to fix this, only when converting to PDF (the .ipynb and HTML versions were working fine).

If anyone is interested, it is (of course) open-source: https://github.com/Naereen/fix-iocaml-notebook-exports-to-pdf

**Comment by akabe** [comment]
@Naereen I re-implemented iocaml as ocaml-jupyter: https://github.com/akabe/ocaml-jupyter due to some reasons including this issue, ppx support, and so on. I checked my notebooks can be converted by nbconvert. Please try if you are interested.

**Comment by Naereen** [comment]
@akabe Awesome!
It looks amazing! :clap:

I will try it next week and if my previous notebooks can be easily ported to the new kernel, then the baby tool I coded will be useless, hopefully!
Thanks for letting me (us) know.

**Comment by Naereen** [comment]
@akabe OK I have been able to change from iocaml kernel to your version, for one of my preexisting notebook, without any issue!
Great job!
