### ISSUE TITLE
Maintenance status? Do you want help maintaining?

### ISSUE THREAD

**Issue by jaredly** [andrewray/iocaml#62]
Hi! I contributed some bugfixes last ~june, and at the time you talked about releasing a new version with them included. There hasn't been any activity on this repo since :(
Are you still invested in the project? I'd be happy to help maintain if that's something you're looking for.

Cheers!

**Comment by andrewray** [comment]
I would very much appreciate your help.

I will give you commit rights.

**Comment by jaredly** [comment]
thanks!
