### ISSUE TITLE
`disagree over interface Log`while loading `owl`

### ISSUE THREAD

**Issue by ryanrhymes** [andrewray/iocaml#69]
Hi,

I was trying to load `owl` in `iocaml`, but it complains

```text
The files /Users/liang/.opam/4.04.0/lib/owl_zoo/owl_zoo.cma
and /Users/liang/.opam/4.04.0/bin/iocaml.top
disagree over interface Log
```

I guess the reason is that Owl uses [Dolog](https://github.com/UnixJunkie/dolog) which also has a module called `Log`. Is it possible to resolve this by renaming one of your Log modules? @UnixJunkie many thanks.

Liang

**Comment by UnixJunkie** [comment]
You can contribue to dolog then: pass it under jbuilder, then it would create a module Dolog and Log would become Dolog.Log. Your contribution to dolog will be welcome. I would accept it and create a major dolog release.
